#!/usr/bin/env python3
"""
case/36.passive_pseudoshock_control 用 2D 平面メッシュ生成スクリプト。

Matsuo et al. (1988) "境界層のパッシブコントロールが擬似衝撃波に及ぼす影響"
(九州大学総合理工学研究科報告 10(1), pp.45-50) の試験部形状を 2D 平面で再現する。

- forge は gmsh `.msh` を `convertGmshToForge` 経由で読む。2D 平面メッシュ
  (2D 面要素 + 1D 境界線要素) はそのまま 2D ソルバとして扱われる (gmshReader.hpp の
  is3D 自動判定)。よって押し出しは不要で、Physical Curve = 境界 physID、
  Physical Surface = 流体領域 となる。
- 全寸法は mm で記述し、出力時に 0.001 倍して [m] にする (forge は SI)。

座標系: x = 流れ方向 (右が下流), y = 上下 (中心線 y=0, 上下対称), z 無し。
原点 x=0 はダクト入口 (助走領域の左端)。

本フェーズの領域 (パラメトリック):
  x=0     入口 inlet
  x=30    助走領域 (slip) -> 1deg 拡大ダクト (no-slip) の壁切替点
  x=130   キャビティ部 (多孔壁) 上流端
  x=162   キャビティ部 下流端 (=130+32)
  x=690   出口 outlet (=162+528)  ※10deg ディフューザ/チャンバは後段で追加

POROUS=True  : 上下壁にスロット+キャビティ (多孔壁)
POROUS=False : x[130,162] は連続 no-slip 壁 (固体壁・比較基準)
"""
import math

# ----------------------------------------------------------------------------
# パラメータ
# ----------------------------------------------------------------------------
POROUS = True            # True: 多孔壁+キャビティ, False: 固体壁
OUTFILE = "passive_porous.geo" if POROUS else "passive_solid.geo"

# --- 形状 [mm] ---
HIN_HALF = 10.7545       # 入口半高さ (入口高さ 21.509mm, M_in=1.689)
TAN1 = math.tan(math.radians(1.0))   # 片側 1deg こう配
X_IN   = 0.0
X_RUN  = 30.0            # 助走領域端 (slip->no-slip)
X_C0   = 130.0           # キャビティ部 上流端
X_C1   = 162.0           # キャビティ部 下流端
X_OUT  = 690.0           # 出口

PLATE_T = 2.0            # 多孔板厚
CAV_D   = 20.0           # キャビティ深さ
N_SLOT  = 8              # スロット本数 (流れ方向)
SLOT_PITCH = 4.0         # スロットピッチ
SLOT_W  = 0.8            # スロット幅 (開口率 8*0.8/32 = 0.2)
SLOT_C0 = X_C0 + 2.0     # 最初のスロット中心 (=132)

# --- メッシュ密度 ---
NY      = 120            # ダクト高さ方向セル数 (wall-resolved 化で増)
BUMP    = 0.02           # 壁近傍クラスタリング (小さいほど壁に密; 第一セル ~4um -> y+~30-80)
NX_RUN  = 50             # 助走領域 流れ方向セル数
NX_DIFF = 125            # 拡大ダクト
NX_DOWN = 380            # 下流直管 (528mm; 出口側セルを抑えAR<1000維持)

# 構造ブロックの流れ方向クラスタリング (pave コアとの界面を寄せる)
DIFF_BUMP = 0.35         # 拡大ダクト: 両端 (x=30,130) を細かく (Bump<1)
DOWN_PROG = 1.0075       # 下流直管: x=162 (キャビティ側) を細かく (+x 方向 Progression)

# 特性長 [m] (非構造領域のみ有効)
CL_CORE = 0.0003
CL_SLOT = 0.00015
CL_CAV  = 0.0006

SCALE = 0.001            # mm -> m


def yw(x):
    """中心線からの半高さ [mm]。"""
    if x <= X_RUN:
        return HIN_HALF
    return HIN_HALF + (x - X_RUN) * TAN1


# ----------------------------------------------------------------------------
# .geo ビルダ (built-in kernel)
# ----------------------------------------------------------------------------
class Geo:
    def __init__(self):
        self._pid = 0
        self._lid = 0
        self._sid = 0
        self.points = {}        # (x,y) -> id   (mm キー)
        self.lines = {}         # (pa,pb) -> id (正方向)
        self.geo_pts = []       # (id, x, y, cl)  [m]
        self.geo_lines = []     # (id, pa, pb)
        self.tf_curves = {}     # lid -> (N, bump or None)
        self.surfaces = []      # (sid, [signed line ids], transfinite?)

    def P(self, x, y, cl):
        key = (round(x, 5), round(y, 5))
        if key in self.points:
            return self.points[key]
        self._pid += 1
        self.points[key] = self._pid
        self.geo_pts.append((self._pid, x * SCALE, y * SCALE, cl))
        return self._pid

    def L(self, pa, pb):
        if (pa, pb) in self.lines:
            return self.lines[(pa, pb)]
        if (pb, pa) in self.lines:
            return -self.lines[(pb, pa)]
        self._lid += 1
        self.lines[(pa, pb)] = self._lid
        self.geo_lines.append((self._lid, pa, pb))
        return self._lid

    def tf(self, signed_lid, n, mode=None, val=None):
        # mode: None / "Bump" / "Progression"
        self.tf_curves[abs(signed_lid)] = (n, mode, val)

    def surf(self, signed_lines, transfinite=False):
        self._sid += 1
        self.surfaces.append((self._sid, signed_lines, transfinite))
        return self._sid

    def write(self, path):
        out = []
        out.append("// auto-generated by make_mesh.py — do not edit by hand")
        out.append("SetFactory(\"Built-in\");")
        out.append("Mesh.RecombineAll = 1;")
        out.append("Mesh.Algorithm = 6;            // Frontal-Delaunay (robust)")
        out.append("Mesh.RecombinationAlgorithm = 1;  // Blossom")
        out.append("Mesh.RecombineOptimizeTopology = 5;")
        out.append("")
        for pid, x, y, cl in self.geo_pts:
            out.append(f"Point({pid}) = {{{x:.8g}, {y:.8g}, 0, {cl:.6g}}};")
        out.append("")
        for lid, pa, pb in self.geo_lines:
            out.append(f"Line({lid}) = {{{pa}, {pb}}};")
        out.append("")
        for lid, (n, mode, val) in sorted(self.tf_curves.items()):
            if mode is None:
                out.append(f"Transfinite Curve {{{lid}}} = {n};")
            else:
                out.append(f"Transfinite Curve {{{lid}}} = {n} Using {mode} {val};")
        out.append("")
        for sid, signed, tfin in self.surfaces:
            loop = ", ".join(str(s) for s in signed)
            out.append(f"Curve Loop({sid}) = {{{loop}}};")
            out.append(f"Plane Surface({sid}) = {{{sid}}};")
            if tfin:
                out.append(f"Transfinite Surface {{{sid}}};")
            out.append(f"Recombine Surface {{{sid}}};")
        out.append("")
        return out


g = Geo()

# ----------------------------------------------------------------------------
# ダクト本体ブロック (transfinite 構造)
# 各ブロック: 4 隅 (左下,右下,右上,左上) を反時計回り。
# 壁=上下水平線, 鉛直線=入口/ブロック境界。
# ----------------------------------------------------------------------------
wall_slip = []     # physID 3
wall_noslip = []   # physID 4
inlet_lines = []
outlet_lines = []

def duct_block(xa, xb, nx, slip_wall, sdist=None):
    """xa->xb のダクト矩形ブロック (transfinite)。
    sdist: 流れ方向分布 None / ("Bump", b) / ("Progression", p) (+x 方向に適用)。
    戻り値: (l_left, l_bottom, l_right, l_top_fwd) signed line ids。"""
    pbl = g.P(xa, -yw(xa), CL_CORE)
    pbr = g.P(xb, -yw(xb), CL_CORE)
    ptr = g.P(xb,  yw(xb), CL_CORE)
    ptl = g.P(xa,  yw(xa), CL_CORE)
    l_bottom = g.L(pbl, pbr)        # +x
    l_top    = g.L(ptl, ptr)        # +x (forward; ループでは -l_top)
    l_right  = g.L(pbr, ptr)        # 上
    l_left   = g.L(ptl, pbl)        # 下
    mode = sdist[0] if sdist else None
    val = sdist[1] if sdist else None
    g.tf(l_bottom, nx + 1, mode, val)
    g.tf(l_top, nx + 1, mode, val)
    g.tf(l_right, NY + 1, "Bump", BUMP)
    g.tf(l_left, NY + 1, "Bump", BUMP)
    g.surf([l_bottom, l_right, -l_top, l_left], transfinite=True)
    wlist = wall_slip if slip_wall else wall_noslip
    wlist.append(abs(l_bottom))
    wlist.append(abs(l_top))
    return l_left, l_bottom, l_right, l_top


# 助走領域 (slip), 入口左端
l_left, _, _, _ = duct_block(X_IN, X_RUN, NX_RUN, slip_wall=True)
inlet_lines.append(abs(l_left))

# 拡大ダクト (no-slip): 両端を細かく → x=130 でコア pave と寄せる
duct_block(X_RUN, X_C0, NX_DIFF, slip_wall=False, sdist=("Bump", DIFF_BUMP))

# (キャビティ部 core は下で個別構築)

# 下流直管 (no-slip), 出口右端: x=162 (キャビティ側) を細かく
_, _, l_right_out, _ = duct_block(X_C1, X_OUT, NX_DOWN, slip_wall=False,
                                  sdist=("Progression", DOWN_PROG))
outlet_lines.append(abs(l_right_out))


# ----------------------------------------------------------------------------
# キャビティ部 core (x[130,162]) — 非構造。上下端はスロット口で分割。
# ----------------------------------------------------------------------------
slot_centers = [SLOT_C0 + i * SLOT_PITCH for i in range(N_SLOT)]
slots = [(c - SLOT_W / 2, c + SLOT_W / 2) for c in slot_centers]

# core 左右の鉛直線 (拡大ダクト右端 / 下流直管左端と共有 -> 同一 line)
c_pbl = g.P(X_C0, -yw(X_C0), CL_CORE)
c_ptl = g.P(X_C0,  yw(X_C0), CL_CORE)
c_pbr = g.P(X_C1, -yw(X_C1), CL_CORE)
c_ptr = g.P(X_C1,  yw(X_C1), CL_CORE)
core_left  = g.L(c_ptl, c_pbl)   # 上->下 (拡大ダクト右端の逆向き)
core_right = g.L(c_pbr, c_ptr)   # 下->上
g.tf(core_left, NY + 1, "Bump", BUMP)
g.tf(core_right, NY + 1, "Bump", BUMP)


def top_edge_lines(sign):
    """sign=+1: 上壁, -1: 下壁。core の壁線 (左->右) を slot 口で分割して返す。
    戻り値: (edge_signed_lines[左->右], mouth_lines[各スロット口 line id])。"""
    y = lambda xx: sign * yw(xx)
    cl = CL_CORE
    edge = []
    mouths = []
    x_prev = X_C0
    p_prev = g.P(X_C0, y(X_C0), cl)
    if POROUS:
        for (sl, sr) in slots:
            # 壁セグメント x_prev -> sl
            p_sl = g.P(sl, y(sl), CL_SLOT)
            seg = g.L(p_prev, p_sl)
            edge.append(seg)
            wall_noslip.append(abs(seg))
            # スロット口 sl -> sr (内部境界, 壁にしない)
            p_sr = g.P(sr, y(sr), CL_SLOT)
            mouth = g.L(p_sl, p_sr)
            edge.append(mouth)
            mouths.append(mouth)
            p_prev = p_sr
        # 最後の壁セグメント -> X_C1
        p_end = g.P(X_C1, y(X_C1), cl)
        seg = g.L(p_prev, p_end)
        edge.append(seg)
        wall_noslip.append(abs(seg))
    else:
        p_end = g.P(X_C1, y(X_C1), cl)
        seg = g.L(p_prev, p_end)
        edge.append(seg)
        wall_noslip.append(abs(seg))
    return edge, mouths


top_edge, top_mouths = top_edge_lines(+1)     # 左->右
bot_edge, bot_mouths = top_edge_lines(-1)     # 左->右 (下壁)

# core ループ (反時計回り): 下壁(左->右) , 右(下->上), 上壁(右->左), 左(上->下)
core_loop = []
core_loop += bot_edge                      # 下壁 左->右
core_loop += [core_right]                  # 右 下->上
core_loop += [-s for s in reversed(top_edge)]  # 上壁 右->左
core_loop += [core_left]                   # 左 上->下
g.surf(core_loop, transfinite=False)


# ----------------------------------------------------------------------------
# キャビティ + スロット (上下の comb) — 非構造
# ----------------------------------------------------------------------------
def build_comb(sign, mouths):
    """sign=+1 上側, -1 下側。mouths は core 上/下壁のスロット口 line (左->右)。"""
    Yf = lambda xx: sign * (yw(xx) + PLATE_T)          # キャビティ床
    Yc = lambda xx: sign * (yw(xx) + PLATE_T + CAV_D)  # キャビティ天井
    ywall = lambda xx: sign * yw(xx)

    loop = []
    # 床左端
    p_A = g.P(X_C0, Yf(X_C0), CL_CAV)
    p_prev = p_A
    for i, (sl, sr) in enumerate(slots):
        # 床セグメント p_prev -> slot 床左
        p_ff = g.P(sl, Yf(sl), CL_SLOT)
        seg = g.L(p_prev, p_ff)
        loop.append(seg); wall_noslip.append(abs(seg))
        # スロット左側壁 (床 -> 壁)
        p_wl = g.P(sl, ywall(sl), CL_SLOT)
        sidel = g.L(p_ff, p_wl)
        loop.append(sidel); wall_noslip.append(abs(sidel))
        # スロット口 (= core と共有, 内部境界)。core 側 mouth は p(sl)->p(sr)。
        # comb 側はそれを使う (符号は L() が解決)。
        p_wr = g.P(sr, ywall(sr), CL_SLOT)
        loop.append(g.L(p_wl, p_wr))
        # スロット右側壁 (壁 -> 床)
        p_fr = g.P(sr, Yf(sr), CL_SLOT)
        sider = g.L(p_wr, p_fr)
        loop.append(sider); wall_noslip.append(abs(sider))
        p_prev = p_fr
    # 床セグメント -> 右端
    p_B = g.P(X_C1, Yf(X_C1), CL_CAV)
    seg = g.L(p_prev, p_B)
    loop.append(seg); wall_noslip.append(abs(seg))
    # 右側壁 (床 -> 天井)
    p_C = g.P(X_C1, Yc(X_C1), CL_CAV)
    rw = g.L(p_B, p_C)
    loop.append(rw); wall_noslip.append(abs(rw))
    # 天井 (右 -> 左)
    p_D = g.P(X_C0, Yc(X_C0), CL_CAV)
    ceil = g.L(p_C, p_D)
    loop.append(ceil); wall_noslip.append(abs(ceil))
    # 左側壁 (天井 -> 床)
    lw = g.L(p_D, p_A)
    loop.append(lw); wall_noslip.append(abs(lw))

    # comb は床側が下向き (上側 comb のとき) で時計回りになる場合があるが、
    # Plane Surface は閉ループであれば向きに依らずメッシュ可能。
    g.surf(loop, transfinite=False)


if POROUS:
    build_comb(+1, top_mouths)
    build_comb(-1, bot_mouths)


# ----------------------------------------------------------------------------
# Physical groups
# ----------------------------------------------------------------------------
lines_block = g.write(OUTFILE)

# 重複除去
wall_slip_u = sorted(set(wall_slip))
wall_noslip_u = sorted(set(wall_noslip))
inlet_u = sorted(set(inlet_lines))
outlet_u = sorted(set(outlet_lines))
all_surfs = [s[0] for s in g.surfaces]

phys = []
phys.append(f'Physical Curve("inlet", 1) = {{{", ".join(map(str, inlet_u))}}};')
phys.append(f'Physical Curve("outlet", 2) = {{{", ".join(map(str, outlet_u))}}};')
phys.append(f'Physical Curve("wall_slip", 3) = {{{", ".join(map(str, wall_slip_u))}}};')
phys.append(f'Physical Curve("wall", 4) = {{{", ".join(map(str, wall_noslip_u))}}};')
phys.append(f'Physical Surface("fluid", 10) = {{{", ".join(map(str, all_surfs))}}};')

with open(OUTFILE, "w") as f:
    f.write("\n".join(lines_block))
    f.write("\n".join(phys))
    f.write("\n")

print(f"wrote {OUTFILE}")
print(f"  POROUS={POROUS}  surfaces={len(all_surfs)}  points={g._pid}  lines={g._lid}")
print(f"  inlet lines={inlet_u}")
print(f"  outlet lines={outlet_u}")
print(f"  wall_slip lines={len(wall_slip_u)}  wall(no-slip) lines={len(wall_noslip_u)}")
print(f"  yw: in={yw(0):.4f} cav0={yw(130):.4f} cav1={yw(162):.4f} out={yw(690):.4f} (mm half-height)")
