inlet:
  physID: 1
  kind: inlet_Pressure
  outputHDFflg: 0
  ints:
  floats:
    Pt: 2000000.3987
    Tt: 353.0

outlet:
  physID: 2
  #kind: outlet_statPress
  kind: outflow
  outputHDFflg: 0
  ints:
  floats:
    Ps: 600000.0
    Pt: 600000.0 # backflow
    Tt: 353.0    # backflow

wall:
  physID: 3
  kind: wall
  outputHDFflg: 0
  ints:
  floats:


