inlet:
  physID: 1 
  kind: inlet_uniformVelocity
  ints:
  floats:
    Ux: 3.0
    Uy: 0.0
    Uz: 0.0
    ro: 1.4
    Ps: 1.0

top:
  physID: 2
  kind: slip
  ints:
  floats:

bottom:
  physID: 3
  kind: slip
  ints:
  floats:

wall:
  physID: 4
  kind: slip
  ints:
  floats:

outlet:
  physID: 5 
  kind: outflow
  ints:
  floats:

slip:
  physID: 6
  kind: slip
  ints:
  floats:


