mesh:
  meshFormat: "hdf5" 
  meshFileName: "supercritical.h5"
  valueFileName: "supercritical.h5"


gpu: 1 # 0:off , 1:on

#solver: "KEEP_SLAU"
solver: "SLAU"
#solver: "ROE"

physProp:
  isCompressible: 1 # 0:incomp, 1:compressible
  ro : 1.2 # [kg/m3] ignored for compressible flow
  visc : 0.0025 #[Pa*s]
  thermCond: 0.0241 # [W/(mK)]
  cp : 1004.5 # [J/(kgK)]
  gamma : 1.4 # [J/(kgK)]

time: 
  last: 
    control: 0 # 0:nStep , 1:time base
    nStep: 80000
    #nStep: 3
    time: 1.00 # [second]
  deltaT:  
    control: 1 # 0:use dt , 1:use cfl
    dt: 0.00000001
    cfl: 0.3
    dt_min: 0.00000001
    dt_max: 1.0 
  outStepInterval: 500
  #outStepInterval: 1
  timeIntegration: 3  #1:Euler explicit, 3:3rd TVD Runge Explicit, 4:4th runge exp, 10:dual-exp
  implicit:
    nLoop: 10
    cfl_pseudo: 0.5

space: 
  convMethod: 1
  limiter: 1 

turbulence: 
  LESorRANS: 1 # 0:no 1:LES 2:RANS
  LESmodel: 1 # 1:WALE

initial: "supercritical"
