mesh:
  meshFormat: "hdf5" 
  meshFileName: "bump_4pct.h5"
  valueFileName: "bump_4pct.h5"
  #meshFormat: "hdf5" 
  #meshFileName: "mach3.h5"


gpu: 1 # 0:off , 1:on

solver: "SLAU" # 
#solver: "KEEP_SLAU" # 

physProp:
  isCompressible: 1 # 0:incomp, 1:compressible
  thermalMethod: 0 # 0:calorically perfect
  viscMethod: 0 # 0:use visc , 1:sutherland
  ro : 1.4 # [kg/m3] ignored for compressible flow
  visc : 0.0   #[Pa*s]
  thermCond: 0.0    # [W/(mK)]
  cp : 1005.0 # [J/(kgK)]
  gamma : 1.4 # [J/(kgK)]

time: 
  unsteady: 0 # 0:steady , 1:unsteady
  dualTime: 0 # 1:use pseudo time for unsteady
  last: 
    control: 0 # 0:nStep , 1:time base
    #nStep: 8000
    nStep: 2000
    #nStep: 10  
    time: 1.00 # [second]
  deltaT:  
    control: 1 # 0:use dt , 1:use cfl
    dt: 0.00000001
    cfl: 1.5
    cfl_pseudo: 1.0
    dt_min: 0.000000001
    dt_max: 1.0 
  #outStepInterval: 1000
  #outStepInterval: 1
  outStepInterval: 20
  outStepStart: 0
  timeIntegration: 3  # 1:Euler explicit , 3:3rd Runge Explicit , 10:dual-exp
  nInnerLoop: 10

space: 
  convMethod: 2
  limiter: 2

turbulence:
  LESorRANS: 0 # 0:no 1:LES 2:RANS
  LESmodel: 0 # 1:WALE

initial: "bump_M1.65"
