inlet:
  physID: 1
  kind: inlet_uniformVelocity
  ints:
  floats:
    Ux: 2183.0
    Uy: 0.0
    Uz: 0.0
    ro: 0.072
    Ps: 4620.
    Ts: 231.7

outlet:
  physID: 2
  kind: outflow
  #kind: outflow
  ints:
  floats:
    Ps: 4620.
    Pt: 4620.0 # backflow
    Tt: 231.7    # backflow

wall:
  physID: 3
  kind: wall
  #kind: slip
  ints:
  floats:

perio1:
  physID: 4
  kind: slip
  ints:
  floats:

perio2:
  physID: 5
  kind: slip
  ints:
  floats:


slip:
  physID: 6
  kind: slip
  ints:
  floats:


