mesh:
  meshFormat: "hdf5" 
  meshFileName: "mach3_hr.h5"
  valueFileName: "mach3_hr.h5"
  #meshFileName: "laval_nozzle3.h5"


gpu: 1 # 0:off , 1:on

solver: "AUSM+" # SLAU, ROE, AUSM+, AUSM+UP

physProp:
  isCompressible: 1 # 0:incomp, 1:compressible
  ro : 1.4 # [kg/m3] ignored for compressible flow
  visc : 0.0000 #[Pa*s]
  thermCond: 0.0000 # [W/(mK)]
  cp : 2.5    # [J/(kgK)]
  gamma : 1.4 # [J/(kgK)]

time: 
  last: 
    control: 0 # 0:nStep , 1:time base
    nStep: 10000
    #nStep: 10
    time: 1.00 # [second]
  deltaT:  
    control: 1 # 0:use dt , 1:use cfl
    dt: 0.0001
    cfl: 0.5
    dt_min: 0.00000001
    dt_max: 1.0 
  outStepInterval: 100
  #outStepInterval: 100
  #outStepInterval: 1
  timeIntegration: 3  #1:Euler explicit, 3:3rd TVD Runge Explicit, 4:4th runge exp, 10:dual-exp
  implicit:
    nLoop: 10
    cfl_pseudo: 0.5

space: 
  convMethod: 0 # 0:1stUp 1:2nd 2:MUSCL
  limiter: 2    # 0:off   1:venkata

turbulence:
  LESorRANS: 0 # 0:no 1:LES 2:RANS
  LESmodel: 0 # 1:WALE

initial: "mach3"
