inlet:
  physID: 1 
  kind: inlet_uniformVelocity
  #kind: periodic
  ints:
  floats:
    ro: 0.02026
    Ps: 370.5657326
    Ux: 1296.22 
    Uy: 0.0
    Uz: 0.0

outlet:
  physID: 2
  kind: outflow
  ints:
  floats:

wall:
  physID: 3
  kind: slip
  ints:
  floats:

perio1:
  physID: 4
  kind: slip
  ints:
    type: 0
    partnerBCID: 1
  ints:
  floats:
    Ps: 101325.0

perio2:
  physID: 5
  kind: slip
  ints:
  floats:


