inlet:
  physID: 1 
  kind: inlet_uniformVelocity
  ints:
  floats:
    #Ux: 3.0
    Ux: 3.0
    Uy: 0.0
    Uz: 0.0
    ro: 1.4
    Ps: 1.0

top:
  physID: 2
  kind: slip
  ints:
  floats:

bottom:
  physID: 3
  kind: slip
  ints:
  floats:

wall:
  physID: 4
  kind: slip
  ints:
  floats:

outlet:
  physID: 5 
  kind: outflow
  ints:
  floats:

slip1:
  physID: 6
  kind: slip
  ints:
    type: 0 #0:cartesian , 1:rotation
    partnerBCID: 7
  floats:

slip2:
  physID: 7
  kind: slip
  ints:
    type: 0 #0:cartesian , 1:rotation
    partnerBCID: 6
  floats:



