inlet:
  physID: 1
  kind: inlet_uniformVelocity
  outputHDFflg: 0
  ints:
  floats:
    ro: 0.03959455178967375
    Ux: 1783.8878888540053 
    Uy: 0.0
    Uz: 0.0
    Ps: 2500.0

outlet:
  physID: 2
  kind: outflow
  outputHDFflg: 0
  ints:
  floats:
    Pt: 2500.0 # backflow
    Tt: 220.0  # backflow

wall:
  physID: 3
  kind: wall
  outputHDFflg: 0
  ints:
  floats:
    Ux: 0.0
    Uy: 0.0
    Uz: 0.0

bot:
  physID: 4
  kind: slip
  outputHDFflg: 0
  ints:
  floats:

top:
  physID: 5
  kind: slip
  outputHDFflg: 0
  ints:
  floats:

side1:
  physID: 6
  kind: slip
  outputHDFflg: 0
  ints:
  floats:

side2:
  physID: 7
  kind: slip
  outputHDFflg: 0
  ints:
  floats:
    Ux: 0.0
    Uy: 0.0
    Uz: 0.0
