inlet:
  physID: 1
  kind: inlet_fluctVelocity
  outputHDFflg: 0
  ints:
  floats:
    Ux0: 860.747963
    Uy0: 0.0
    Uz0: 0.0
    ro: 0.04120110420717082
    Ps: 605.662
    Ts: 51.22

outlet:
  physID: 2
  kind: outflow
  outputHDFflg: 1
  #kind: outflow
  ints:
  floats:
    Ps: 605.662
    Pt: 605.662
    Tt: 51.22 

wall:
  physID: 3
  kind: wall_isothermal
  outputHDFflg: 1
  #kind: slip
  ints:
  floats:
    Ux: 0.0
    Uy: 0.0
    Uz: 0.0
    Ts: 300.0

axis:
  physID: 4
  kind: slip
  outputHDFflg: 0
  ints:
  floats:


side1:
  physID: 5
  kind: slip
  outputHDFflg: 0
  ints:
  floats:

side2:
  physID: 6
  kind: slip
  outputHDFflg: 0
  ints:
  floats:



