inlet:
  physID: 1
  kind: inlet_Pressure
  ints:
  floats:
    Pt: 59100
    Tt: 286.65

outlet:
  physID: 2
  #kind: outlet_statPress
  kind: outflow
  ints:
  floats:
    Pt: 55100.0  # backflow
    Tt: 286.65   # backflow

wall:
  physID: 3
  kind: wall
  ints:
  floats:


