inlet:
  physID: 1
  kind: inlet_Pressure
  outputHDFflg: 0
  ints:
  floats:
    Pt: 100000.0
    Tt: 288.15

outlet:
  physID: 2
  kind: outlet_statPress
  #kind: outflow
  outputHDFflg: 0
  ints:
  floats:
    Ps: 99118.333
    Pt: 99118.333 # backflow
    Tt: 288.15    # backflow

top:
  physID: 3
  kind: wall
  outputHDFflg: 0
  ints:
  floats:
    Ux: 0.0
    Uy: 0.0
    Uz: 0.0

bot:
  physID: 4
  kind: wall
  outputHDFflg: 0
  ints:
  floats:
    Ux: 0.0
    Uy: 0.0
    Uz: 0.0

sidel1:
  physID: 5
  kind: slip
  outputHDFflg: 0
  ints:
  floats:
    Ux: 0.0
    Uy: 0.0
    Uz: 0.0

sidel2:
  physID: 6
  kind: slip
  outputHDFflg: 0
  ints:
  floats:
    Ux: 0.0
    Uy: 0.0
    Uz: 0.0
