mesh:
  meshFormat: "hdf5" 
  meshFileName: "backstep.h5"
  valueFileName: "input.h5"


gpu: 1 # 0:off , 1:on

#solver: "KEEP_SLAU" # SLAU, ROE, AUSM+, AUSM+UP, KEEP_SLAU
solver: "SLAU" # SLAU, ROE, AUSM+, AUSM+UP, KEEP_SLAU
#solver: "ROE" # SLAU, ROE, AUSM+, AUSM+UP, KEEP_SLAU

physProp:
  isCompressible: 1 # 0:incomp, 1:compressible
  thermalMethod: 0 # 0:calorically perfect
  viscMethod: 0 # 0:use visc , 1:sutherland
  ro : 1.2 # [kg/m3] ignored for compressible flow
  visc : 0.001  #[Pa*s]
  #visc : 0.000  #[Pa*s]
  thermCond: 0.0241 # [W/(mK)]
  cp : 1004.5 # [J/(kgK)]
  gamma : 1.4 # [J/(kgK)]

time: 
  unsteady: 0 # 0:steady , 1:unsteady
  dualTime: 0 # 1:use pseudo time for unsteady
  last: 
    control: 0 # 0:nStep , 1:time base
    #nStep: 10000
    nStep: 500
    #nStep: 200
    time: 1.00 # [second]
  deltaT:  
    control: 1 # 0:use dt , 1:use cfl 
    dt: 0.0001
    cfl: 1.0
    cfl_pseudo: 1.0 # for pseudo dt
    dt_min: 0.000000001
    dt_max: 1.0 
  outStepStart: 0
  outStepInterval: 1
  #outStepInterval: 1
  timeIntegration: 3  #1:Euler explicit, 3:3rd TVD Runge Explicit, 4:4th runge exp, 10:dual-exp
  nInnerLoop: 10

space: 
  convMethod: 2 # 0:1stUp 1:2ndup 2:MUSCL
  limiter: 2 # 1:barth 2:venkata

turbulence:
  LESorRANS: 0 # 0:no 1:LES 2:RANS
  LESmodel: 1 # 1:WALE

initial: "backstep"

