inlet:
  physID: 1
  kind: inlet_uniformVelocity
  ints:
  floats:
    Ux: 873.964395
    Uy: 0.0
    Uz: 0.0
    ro: 0.03888
    Ps: 589.22776
    Ts: 52.805

outlet:
  physID: 2
  kind: outflow
  #kind: outflow
  ints:
  floats:
    Ps: 589.2277607999999
    Pt: 589.2277607999999 # backflow
    Tt: 52.805    # backflow

wall:
  physID: 3
  kind: wall
  #kind: slip
  ints:
  floats:

perio1:
  physID: 4
  kind: slip
  ints:
  floats:

perio2:
  physID: 5
  kind: slip
  ints:
  floats:


slip:
  physID: 6
  kind: slip
  ints:
  floats:


