mesh:
  meshFormat: "hdf5" 
  meshFileName: "bump_4pct.h5"
  valueFileName: "bump_4pct.h5"
  #meshFormat: "hdf5" 
  #meshFileName: "mach3.h5"


gpu: 1 # 0:off , 1:on

solver: "SLAU" # 

physProp:
  isCompressible: 1 # 0:incomp, 1:compressible
  ro : 1.4 # [kg/m3] ignored for compressible flow
  visc : 0.0025 #[Pa*s]
  thermCond: 0.0241 # [W/(mK)]
  cp : 1005.0 # [J/(kgK)]
  gamma : 1.4 # [J/(kgK)]

time: 
  last: 
    control: 0 # 0:nStep , 1:time base
    nStep: 50000
    time: 1.00 # [second]
  deltaT:  
    control: 1 # 0:use dt , 1:use cfl
    dt: 0.00000001
    cfl: 0.50
    dt_min: 0.000000001
    dt_max: 1.0 
  outStepInterval: 1000
  timeIntegration: 3  # 1:Euler explicit , 3:3rd Runge Explicit , 10:dual-exp
  implicit:
    nLoop: 100
    cfl_pseudo: 0.5

space: 
  convMethod: 1
  limiter: 1

initial: "bump"
