bottom:
  physID: 1
  kind: slip
  ints:
  floats:

upper:
  physID: 2
  kind: slip
  ints:
  floats:

slip:
  physID: 3
  kind: slip
  ints:
  floats:

inlet:
  physID: 4 
  kind: slip 
  ints:
  floats:

outlet:
  physID: 5 
  kind: slip
  ints:
  floats:

