inlet:
  physID: 1
  kind: inlet_Pressure
  ints:
  floats:
    Pt: 2000000.3987
    Tt: 353.0

outlet:
  physID: 2
  #kind: outlet_statPress
  kind: outflow
  ints:
  floats:
    #Ps: 600000.0
    Tt: 350.0
    Pt: 600000.0

wall:
  physID: 3
  kind: wall
  #kind: slip
  ints:
  floats:


