#!/usr/bin/env python3
"""M4.19 加熱空気風洞の推奨形状 の**完全な壁輪郭**を点列 CSV と gmsh .geo に書き出す。

**Euler 版と NS 版の 2 つ**を出す:
  - euler: 非粘性設計壁そのもの (`AxisMachCFDWall`) = 推奨 run が実際に解いた形状
  - ns   : 物理壁 (`PhysicalNozzleWall`, A13) = 非粘性壁 + 排除厚 δ*(s) の法線オフセット。
           真の幾何スロートを再探索し上流 Hermite を作り直すので、スロートが僅かに上流へずれる。
           **実機の壁 (境界層を持つ実流で設計コアを実現する形状) はこちら**。

生産経路 (`runner_axismach.prepare`) は構造化 TFI メッシュを msh4.1 で直接書くので .geo を
経由しない。本スクリプトは**外部 (CAD・他ソルバ・他メッシャ) 向け**に、同一の壁定義から
  (1) points_va_best.csv     : 全輪郭点列 [m] (入口直管 → 収縮 Hermite → スロート → MOC 設計壁 → 出口)
  (2) nozzle_va_best.geo     : gmsh スクリプト (軸対称半平面、構造化 quad、forge physID 規約)
を生成する。壁の数式表現は README の「M4.2 形状の数式」節を参照。

usage: design/.venv-opt/bin/python case/44.vitiated_air_wt/export_wall_va.py [--problem YAML] [--n 800] [--ni 365] [--nj 65]
"""
import argparse, sys
from pathlib import Path
import numpy as np
sys.path.insert(0, "/home/sano/work/forge/design")
from forge_design.evaluate.runner_axismach import design_chain
from forge_design.probdef import load_problem

CASE = Path("/home/sano/work/forge/case/44.vitiated_air_wt")
ap = argparse.ArgumentParser()
ap.add_argument("--problem", default=str(CASE / "problem_va_R2_LU6_Lc8.yaml"))
ap.add_argument("--n", type=int, default=800, help="輪郭出力点数 (壁曲線)")
ap.add_argument("--ni", type=int, default=365, help="gmsh 軸方向分割 (生産メッシュと同じ)")
ap.add_argument("--nj", type=int, default=65, help="gmsh 半径方向分割")
ap.add_argument("--wall-first-frac", type=float, default=5.0e-3, help="壁第一層の相対厚 (Bump 用)")
ap.add_argument("--kind", choices=("euler", "ns", "both"), default="both")
ap.add_argument("--tag", default="va_best")
ap.add_argument("--dstar-csv", default=None, help="NS 版の δ*(x) を CSV [x_rt, dstar_rt] で与える (CFD 抽出の固定点、全域採用)。省略時は相関 (v1)")
a = ap.parse_args()

p = load_problem(a.problem)
d = design_chain(p)
s = float(p.spec["r_throat"])          # r_t [m]


def build(kind):
    if kind == "euler":
        return d["wall"], "inviscid design wall (AxisMachCFDWall)"
    from forge_design.evaluate.runner_axismach import _gam_or_gas
    from forge_design.geometry.wall_axismach import PhysicalNozzleWall
    dstar_x = None
    if a.dstar_csv:
        tbl = np.loadtxt(a.dstar_csv, delimiter=",", skiprows=1)
        dstar_x = lambda x, _t=tbl: np.interp(np.clip(np.asarray(x, float), _t[0, 0], _t[-1, 0]), _t[:, 0], _t[:, 1])
    pw = PhysicalNozzleWall(d["wall"], d["wall_inv"], s, float(p.spec["Pt"]),
                            float(p.spec["Tt"]), _gam_or_gas(p), p.cp, dstar_x=dstar_x)
    msgs = pw.validate()
    if msgs:
        raise RuntimeError("PhysicalNozzleWall validate: " + "; ".join(msgs))
    return pw, "physical wall = inviscid + delta* normal offset (PhysicalNozzleWall%s)" % (f", delta* from {Path(a.dstar_csv).name}" if a.dstar_csv else ", correlation delta*")


def export(w, desc, kind, out_csv, out_geo):
    x_thr = float(getattr(w, "x_throat", 0.0))
    r_thr = float(getattr(w, "r_throat", 1.0))
    L_U = w.up.L_U if hasattr(w, "up") else w.L_U
    x_hermite0 = -L_U
    # --- 輪郭点列 (無次元 x/r_t → m)。区間ごとに分けて端点を厳密に含める ---
    xs = np.concatenate([
        np.linspace(w.x_in, x_hermite0, 30),                       # 入口直管
        np.linspace(x_hermite0, x_thr, max(a.n // 4, 60))[1:],       # U→T 収縮 (5 次 Hermite)
        np.linspace(x_thr, w.x_e, a.n)[1:],                         # スロート → 設計壁 (逆 MOC)
    ])
    rs = w.r(xs)
    np.savetxt(out_csv, np.c_[xs * s, rs * s, xs, rs], delimiter=",",
               header=("x_m,r_m,x_over_rt,r_over_rt\n"
                       f"# M4.19 vitiated-air nozzle [{kind}] {desc}\n"
                       f"# R={d['R']:g}, L_U={L_U:g}, L_c={d['L_c']:g} (r_t units), M_d={d['Md']:g}; r_t={s} m\n"
                       f"# throat x={x_thr*s:.6f} m r={r_thr*s:.6f} m; "
                       f"exit x={w.x_e*s:.6f} m r={float(w.r(np.array([w.x_e]))[0])*s:.6f} m"),
               comments="")
    print(f"wrote {out_csv}: {len(xs)} points, x {xs[0]*s:.4f}..{xs[-1]*s:.4f} m, r {rs.min()*s:.4f}..{rs.max()*s:.4f} m")

    # --- gmsh .geo (軸対称半平面: 下端 = 軸 r=0、上端 = 壁) ---
    xg = np.linspace(w.x_in, w.x_e, a.ni + 1)
    rg = w.r(xg)
    L = [f"// M4.19 vitiated-air wind-tunnel nozzle [{kind}] (axisymmetric half plane, r>=0)",
         f"// {desc}",
         f"// generated by case/44.vitiated_air_wt/export_wall_va.py from {Path(a.problem).name}",
         f"// r_t = {s} m, R = {d['R']:g}, L_U = {L_U:g} r_t, L_c = {d['L_c']:g} r_t, M_d = {d['Md']:g}",
         f"// throat x = {x_thr*s:.6f} m (r = {r_thr*s:.6f} m), exit x = {w.x_e*s:.6f} m (r = {float(w.r(np.array([w.x_e]))[0])*s:.6f} m)",
         "// physical IDs follow the forge convention: inlet 1 / outlet 2 / wall 3 / axis 4 / fluid 5",
         "lc = 1.0;"]
    for i, (x, r) in enumerate(zip(xg, rg), start=1):                 # 壁点
        L.append(f"Point({i}) = {{{x*s:.9g}, {r*s:.9g}, 0, lc}};")
    n = len(xg)
    L.append(f"Point({n+1}) = {{{xg[0]*s:.9g}, 0, 0, lc}};")          # 軸の入口端
    L.append(f"Point({n+2}) = {{{xg[-1]*s:.9g}, 0, 0, lc}};")         # 軸の出口端
    L.append("Spline(1) = {" + ",".join(str(i) for i in range(1, n + 1)) + "};   // wall")
    L.append(f"Line(2) = {{{n+1}, {n+2}}};                            // axis (r=0)")
    L.append(f"Line(3) = {{{n+1}, 1}};                                 // inlet")
    L.append(f"Line(4) = {{{n+2}, {n}}};                               // outlet")
    L += ["Curve Loop(1) = {2, 4, -1, -3};", "Plane Surface(1) = {1};",
          f"Transfinite Curve {{1, 2}} = {a.ni + 1};",
          f"Transfinite Curve {{3, 4}} = {a.nj} Using Bump {a.wall_first_frac};",
          f"Transfinite Surface {{1}} = {{{n+1}, {n+2}, {n}, 1}};", "Recombine Surface{1};",
          'Physical Curve("inlet", 1)  = {3};', 'Physical Curve("outlet", 2) = {4};',
          'Physical Curve("wall", 3)   = {1};', 'Physical Curve("axis", 4)   = {2};',
          'Physical Surface("fluid", 5) = {1};']
    Path(out_geo).write_text("\n".join(L) + "\n")
    print(f"wrote {out_geo}: {a.ni}x{a.nj-1} structured quads "
          f"(gmsh -2 {Path(out_geo).name} -format msh41 -o nozzle_va_best.msh)")

for kind in (("euler", "ns") if a.kind == "both" else (a.kind,)):
    w, desc = build(kind)
    out_csv = CASE / f"points_{a.tag}_{kind}.csv"
    out_geo = CASE / f"nozzle_{a.tag}_{kind}.geo"
    export(w, desc, kind, out_csv, out_geo)

